{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7ca7c0a3-40a2-4b0e-9e84-a8a3e85d5582",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "\n",
    "# Connects to Snowflake using Streamlit's built-in connection manager\n",
    "conn = st.connection(\"snowflake\", type=\"snowflake\")\n",
    "\n",
    "st.title(\"Ecolab Supply Chain Intelligence\")\n",
    "st.markdown(\"### Universal AI Agent (Prompt-Based)\")\n",
    "\n",
    "business_logic = \"\"\"\n",
    "You are a Snowflake SQL expert. Use these EXACT table and column names:\n",
    "\n",
    "1. SALES TABLE: ECOLAB_SC_POC.PUBLIC.SALES_DATA\n",
    "   - Use 'ORDER_RECEIVE_DATE' for date on which sales order was booked.\n",
    "   - Use 'ACTUAL_SHIP_DATE' for date on which item or material is actually shipped from warehouse or plant.\n",
    "   - Use 'SHIP_QUANTITY' for actual volume sold or shipped to customer.\n",
    "   - Use 'ORDER_QUANTITY' for volume originally ordered by customer.\n",
    "   - Use 'ACTUAL_DELIVERY_DATE' for date on which material was actually delivered to Customer.\n",
    "   - Use 'REQUESTED_DELIVERY_DATE' for date on which customer expected the material to be delivered.\n",
    "   - Use 'ITEM_NUMBER' and 'PLANT_WAREHOUSE_CODE' to join.\n",
    "\n",
    "2. INVENTORY TABLE: ECOLAB_SC_POC.PUBLIC.ECOLAB_INVENTORY\n",
    "   - Use 'QTY_UNRESTRICTED' as the current stock or Sellable stock.\n",
    "   - Use 'ITEM_NUMBER' and 'LOCATION' to join.\n",
    "\n",
    "3. FORECAST TABLE: ECOLAB_SC_POC.PUBLIC.FORECAST_DATA\n",
    "   - Use 'FORECAST_QTY' for volume (not FORECAST_QUANTITY).\n",
    "   - Use 'MONTH_YEAR' (format MON-YYYY) for date logic.\n",
    "\n",
    "CALCULATIONS:\n",
    "\n",
    "- DOH: QTY_UNRESTRICTED / (SUM(SHIP_QUANTITY in last 180 days) / 180)\n",
    "- DOS: QTY_UNRESTRICTED / (SUM(FORECAST_QTY in next 180 days) / 180)\n",
    "- For DOS 6 Months of forecast from next month, assuming today's month is current month.\n",
    "- OTIF Calculation: (ACTUAL_DELIVERY_DATE <= REQUESTED_DELIVERY_DATE) AND (SHIP_QUANTITY >= ORDER_QUANTITY)\n",
    "- DOH (Days on Hand): CURRENT_STOCK / (Total Sales in last 180 days / 180)\n",
    "- DOS (Days of Supply): CURRENT_STOCK / (Total Forecast in next 180 days / 180)\n",
    "- The FORECAST_DATA table has a MONTH_YEAR string like Mar-2025. Use TO_DATE(MONTH_YEAR, 'MON-YYYY') for logic.\n",
    "\n",
    "Follow these rules strictly:\n",
    "- ONLY return raw SQL. No explanations or introductory text.\n",
    "- Do not use 'DATE_ADD' or 'INTERVAL 1 DAY'. \n",
    "- Instead, use: DATEADD(day, 1, column_name).\n",
    "- Tables: ECOLAB_SC_POC.PUBLIC.SALES_DATA, ECOLAB_SC_POC.PUBLIC.ECOLAB_INVENTORY, ECOLAB_SC_POC.PUBLIC.FORECAST_DATA.\n",
    "- Column mapping: Use QTY_UNRESTRICTED for inventory, ORDER_RECEIVE_DATE for sales, and TO_DATE(MONTH_YEAR, 'MON-YYYY') for forecast.\n",
    "- Never include placeholder text like 'with actual warehouse code' in the SQL.\n",
    "- Use 'CAST(column AS DATE)' or 'DATE(column)' instead of TRUNC().\n",
    "- Ensure all comparisons between dates use the DATE type.\n",
    "- Warehouse codes are case-sensitive; do not guess them unless provided.\n",
    "\"\"\"\n",
    "\n",
    "query = st.text_input(\"Ask a supply chain question:\", placeholder=\"e.g., Which items have DOS > DOH?\")\n",
    "\n",
    "if query:\n",
    "    with st.spinner(\"Generating SQL and analyzing...\"):\n",
    "        prompt = f\"\"\"\n",
    "        {business_logic}\n",
    "        \n",
    "        Question: {query}\n",
    "        \n",
    "        IMPORTANT: Return ONLY the raw SQL code. \n",
    "        Do not include any introductory text like 'Here is the code' or 'Sure'.\n",
    "        Do not use markdown backticks like ```sql.\n",
    "        Just the code.\n",
    "        \"\"\".replace(\"'\", \"''\") \n",
    "        \n",
    "        try:\n",
    "            sql_response = conn.query(f\"SELECT SNOWFLAKE.CORTEX.COMPLETE('llama3-70b', '{prompt}')\").iloc[0,0]\n",
    "            \n",
    "            clean_sql = sql_response.replace(\"```sql\", \"\").replace(\"```\", \"\").strip()\n",
    "            \n",
    "            if \"WITH\" in clean_sql.upper():\n",
    "                clean_sql = clean_sql[clean_sql.upper().find(\"WITH\"):]\n",
    "            elif \"SELECT\" in clean_sql.upper():\n",
    "                clean_sql = clean_sql[clean_sql.upper().find(\"SELECT\"):]\n",
    "\n",
    "            st.write(\"### Generated SQL Query:\")\n",
    "            st.code(clean_sql, language=\"sql\")\n",
    "            \n",
    "            df = conn.query(clean_sql)\n",
    "            st.write(\"### Data Result:\")\n",
    "            st.dataframe(df)\n",
    "            \n",
    "            explanation_prompt = f\"Explain this data result in plain English for a supply chain manager: {df.head(5).to_string()}\"\n",
    "            explanation = conn.query(f\"SELECT SNOWFLAKE.CORTEX.COMPLETE('mistral-large', '{explanation_prompt}')\").iloc[0,0]\n",
    "            st.info(explanation)\n",
    "            \n",
    "        except Exception as e:\n",
    "            st.error(f\"Error: {e}\")\n",
    "            if 'clean_sql' in locals():\n",
    "                st.code(clean_sql, language=\"sql\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
